version: "3.9"
services:
  postgres1:
    image: postgres:latest
    environment:
      POSTGRES_DB: "cofeDB"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "0000"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - db1:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  postgres2:
    image: postgres:latest
    environment:
      POSTGRES_DB: "queueOverFlow"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "0000"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - db2:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  db1:
    driver: local
  db2:
    driver: local