name: build & deploy QueueOverFlow

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and deploy QueueOverFlow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 19
        uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: 19

      - name: Unit test
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean 
          mvn -B package --file pom.xml

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/queueOverFlow:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/queueOverFlow:latest




